In [1]:

import numpy as np
from numba import cuda

In [2]:

@cuda.jit
def matrixMul(A, B, C):
    row, col = cuda.grid(2)
    if row < N and col < K:
        sum_val = 0.0
        for i in range(M):
            sum_val += A[row, i] * B[i, col]
        C[row, col] = sum_val

In [3]:
size = int(input("enter the size of matrix: "))

M = N = K = size

# A = np.random.randn(N, M).astype(np.float32)
A = np.random.randint(2, size=(N, M)).astype(np.float32)
# B = np.random.randn(M, K).astype(np.float32)
B = np.random.randint(2, size=(N, M)).astype(np.float32)
C = np.zeros((N, K), dtype=np.float32)

d_A = cuda.to_device(A)
d_B = cuda.to_device(B)
d_C = cuda.to_device(C)

block_dim = (32, 32)
grid_dim = ((N + block_dim[0] - 1) // block_dim[0], (K + block_dim[1] - 1) // block_dim[1])

matrixMul[grid_dim, block_dim](d_A, d_B, d_C)

C = d_C.copy_to_host()

print(C)

enter the size of matrix: 10


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


[[3. 2. 1. 1. 1. 2. 0. 2. 1. 1.]
 [6. 5. 4. 6. 4. 2. 3. 5. 4. 5.]
 [3. 3. 3. 4. 2. 1. 3. 4. 3. 4.]
 [4. 3. 1. 2. 2. 2. 1. 4. 3. 1.]
 [5. 3. 2. 2. 2. 3. 2. 3. 3. 3.]
 [5. 4. 1. 2. 3. 2. 2. 3. 4. 2.]
 [5. 2. 1. 4. 2. 2. 1. 3. 3. 2.]
 [3. 3. 1. 3. 1. 1. 1. 3. 3. 1.]
 [4. 3. 3. 4. 2. 2. 3. 2. 3. 4.]
 [3. 3. 3. 3. 2. 2. 0. 3. 2. 2.]]


In [4]:
# Certainly! Here's an explanation of the code line by line:

# python
# Copy code
# import numpy as np
# from numba import cuda

# @cuda.jit
# def matrixMul(A, B, C):
#     row, col = cuda.grid(2)
#     if row < N and col < K:
#         sum_val = 0.0
#         for i in range(M):
#             sum_val += A[row, i] * B[i, col]
#         C[row, col] = sum_val
# The code starts by importing necessary libraries: numpy for array operations and cuda from numba for GPU programming.

# @cuda.jit is a decorator provided by numba that marks the following function as a CUDA kernel function. It means that this function will be executed on the GPU.

# matrixMul is the CUDA kernel function for matrix multiplication. It takes three arguments: A, B, and C, representing the input matrices and the resulting matrix.

# row, col = cuda.grid(2) retrieves the thread indices within the 2D grid. Each thread will handle a specific row and column of the resulting matrix.

# if row < N and col < K: ensures that the thread is within the valid range of rows and columns. This is necessary when the matrix size is not a multiple of the block size.

# sum_val = 0.0 initializes a variable to hold the sum of element-wise products during matrix multiplication.

# The following for loop iterates over the range of M, which is the inner dimension of the matrices. It calculates the sum of products of corresponding elements from matrices A and B.

# C[row, col] = sum_val assigns the calculated sum to the corresponding element in the resulting matrix C.

# python
# Copy code
# size = int(input("enter the size of matrix: "))
# M = N = K = size

# A = np.random.randint(2, size=(N, M)).astype(np.float32)
# B = np.random.randint(2, size=(N, M)).astype(np.float32)
# C = np.zeros((N, K), dtype=np.float32)
# size = int(input("enter the size of matrix: ")) prompts the user to enter the size of the square matrix.

# M = N = K = size assigns the value of size to M, N, and K, making them equal. This ensures that the input matrices A and B have compatible dimensions for multiplication.

# A and B are randomly generated matrices with values ranging from 0 to 1. They are created using np.random.randint and cast to np.float32 data type.

# C is initialized as a zero-filled matrix of size (N, K) using np.zeros.

# python
# Copy code
# d_A = cuda.to_device(A)
# d_B = cuda.to_device(B)
# d_C = cuda.to_device(C)
# d_A, d_B, and d_C are device arrays created using cuda.to_device from the original arrays A, B, and C. These device arrays reside in GPU memory.
# python
# Copy code
# block_dim = (32, 32)
# grid_dim = ((N + block_dim[0] - 1) // block_dim[0], (K + block_dim[1] - 1) // block_dim[1])
# block_dim specifies the dimensions of a block of threads. Here, it is set to (32, 32), meaning each block consists of 32x32 threads.

# grid_dim specifies the dimensions of the grid of blocks needed to cover the entire matrix. It is calculated based on the matrix size and block dimensions.

# python
# Copy code
# matrixMul[grid_dim, block_dim](d_A, d_B, d_C)
# This line launches the CUDA kernel function matrixMul on the GPU. It specifies the grid dimensions (grid_dim) and block dimensions (block_dim), followed by the arguments d_A, d_B, and d_C representing the device arrays.
# python
# Copy code
# C = d_C.copy_to_host()
# d_C.copy_to_host() copies the resulting matrix C from GPU memory back to the host (CPU) memory.
# python
# Copy code
# print(C)
# Finally, the resulting matrix C is printed.
# Overall, this code performs matrix multiplication on the GPU using CUDA. It takes the size of the matrix as input, generates random input matrices A and B, performs the matrix multiplication on the GPU, and prints the resulting matrix C.